package proptics.syntax.applied

trait AppliedSyntax extends AppliedTraversalSyntax with AppliedFoldSyntax with AppliedEachSyntax with AppliedFieldsSyntax with AppliedLensSyntax with AppliedConsSyntax
