package proptics.instances

trait AllInstances extends ConsInstances with AtInstances with IndexInstances with FunctorWithIndexInstances with FoldableWithIndexInstances with TraverseWithIndexInstances
