package proptics.syntax

trait AllSyntax
    extends IsoSyntax
    with AnIsoSyntax
    with LensSyntax
    with ALensSyntax
    with PrismSyntax
    with APrismSyntax
    with FoldSyntax
    with TraversalSyntax
    with ATraversalSyntax
    with SetterSyntax
    with IndexedLensSyntax
    with AnIndexedLensSyntax
    with IndexedFoldSyntax
    with IndexedTraversalSyntax
    with FunctionSyntax
    with TupleSyntax
    with StarSyntax
    with CostarSyntax
    with AtSyntax
    with FunctorWithIndexSyntax
    with FoldableWithIndexSyntax
