package proptics.syntax

trait AllSyntax
    extends AtSyntax
    with IsoSyntax
    with EachSyntax
    with FoldSyntax
    with LensSyntax
    with StarSyntax
    with AnIsoSyntax
    with ALensSyntax
    with PrismSyntax
    with TupleSyntax
    with CostarSyntax
    with APrismSyntax
    with SetterSyntax
    with FunctionSyntax
    with TraversalSyntax
    with ATraversalSyntax
    with IndexedLensSyntax
    with IndexedFoldSyntax
    with AnIndexedLensSyntax
    with IndexedTraversalSyntax
    with FunctorWithIndexSyntax
    with FoldableWithIndexSyntax
    with TraverseWithIndexSyntax
